/**
 * Device-tier render settings, decided once at load.
 *
 * Touch devices overwhelmingly pair high-density screens with much weaker
 * GPUs than desktops, so a coarse pointer is the signal that matters here —
 * it costs nothing and needs no user-agent sniffing.
 */
const coarsePointer =
  typeof window !== 'undefined' &&
  typeof window.matchMedia === 'function' &&
  window.matchMedia('(pointer: coarse)').matches;

export const IS_MOBILE = coarsePointer;

/** Extra-constrained devices: few cores and (where reported) little RAM. */
export const IS_LOW_POWER =
  IS_MOBILE &&
  ((navigator.hardwareConcurrency ?? 8) <= 4 ||
    ((navigator as Navigator & { deviceMemory?: number }).deviceMemory ?? 8) <= 4);

/** Canvas dpr range for the main play board. */
export const BOARD_DPR: [number, number] = IS_MOBILE ? [1, 1.25] : [1, 1.5];

/** Canvas dpr range for decorative scenes (home hero, tour). */
export const HERO_DPR: [number, number] = IS_MOBILE ? [1, 1.15] : [1, 1.5];

/** Anisotropic filtering taps — each tap costs texture bandwidth on mobile GPUs. */
export const TEXTURE_ANISOTROPY = IS_MOBILE ? 2 : 4;
export const ROOM_TEXTURE_ANISOTROPY = IS_MOBILE ? 2 : 8;

/** Blurred contact-shadow render target — quarter the pixels on mobile. */
export const CONTACT_SHADOW_RESOLUTION = IS_MOBILE ? 128 : 256;

/*
 * Flying-bead legibility. On phones the board is small and the elevated
 * camera foreshortens vertical motion — a desktop-tuned hop reads as a
 * teleport. Scale the traveling bead up and throw it higher so the arc
 * stays visible on a hand-sized screen.
 */
export const HOP_ARC_BOOST = IS_MOBILE ? 1.6 : 1;
export const FLYER_SCALE_BOOST = IS_MOBILE ? 1.45 : 1;

/*
 * Low-bandwidth asset variants, generated by scripts/build-mobile-assets.sh.
 * Textures: /textures/… → /textures-mobile/… (512px, JPEG q65).
 * HDR IBL:  /hdr/…      → /hdr-mobile/…      (half resolution, same name).
 * Models:   /models/x.glb → /models/x.mobile.glb (simplified + quantized).
 */

export function textureUrl(url: string): string {
  return IS_MOBILE
    ? url.replace('/textures/', '/textures-mobile/').replace('/hdr/', '/hdr-mobile/')
    : url;
}

export function modelUrl(url: string): string {
  return IS_MOBILE ? url.replace('.glb', '.mobile.glb') : url;
}
