/** Re-export unified multiplayer API (implementation lives in ./p2p/). */
export {
  isP2PAvailable,
  isPearDesktop,
  isWebP2PSupported,
  isValidGameState,
  onP2PError,
  onP2PGame,
  onP2PMatchReady,
  onP2PReject,
  onP2PStatus,
  p2pDestroy,
  p2pHost,
  p2pJoin,
  p2pPlay,
  p2pReconnect,
  p2pSnapshot,
  p2pTransport,
  p2pTransportLabel,
  sanitizePlayerName,
  type P2PGamePayload,
  type P2PHostOptions,
  type P2PHostResult,
  type P2PJoinResult,
  type P2PMatchReadyPayload,
  type P2PPlayAction,
  type P2PPlayResult,
  type P2PStatusPayload,
  type P2PTransportKind,
} from './p2p/index';
