import { chromium } from 'playwright';
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const page = await browser.newPage({ viewport: { width: 1280, height: 800 } });
const logs = [];
page.on('console', m => { if (m.type()==='error') logs.push(m.text()); });
page.on('pageerror', e => logs.push(e.message));
await page.goto('http://127.0.0.1:5173/', { waitUntil: 'networkidle' });
await page.getByRole('button', { name: /^Tour$/i }).click();
await page.waitForTimeout(5000);
await page.screenshot({ path: '.tmp-shots/tour-1.png' });
await page.getByRole('button', { name: /^Next$/i }).click();
await page.waitForTimeout(2500);
await page.screenshot({ path: '.tmp-shots/tour-2.png' });
await page.getByRole('button', { name: /^Next$/i }).click();
await page.waitForTimeout(2500);
await page.screenshot({ path: '.tmp-shots/tour-3.png' });
console.log('errors', logs.slice(0, 8));
console.log('canvas', await page.locator('canvas').count());
await browser.close();
