import { chromium } from 'playwright';
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const page = await browser.newPage({ viewport: { width: 1280, height: 800 } });
const logs = [];
page.on('console', m => logs.push([m.type(), m.text()]));
page.on('pageerror', e => logs.push(['pageerror', e.message]));
page.on('requestfailed', r => logs.push(['reqfail', r.url() + ' ' + (r.failure()?.errorText || '')]));
await page.goto('http://127.0.0.1:5173/', { waitUntil: 'networkidle', timeout: 60000 });
await page.waitForTimeout(6000);
const canvas = await page.locator('canvas').count();
const hero = await page.locator('.home-hero-3d').boundingBox();
const fallback = await page.locator('.home-hero-fallback').count();
console.log({ canvas, hero, fallback });
const glInfo = await page.evaluate(() => {
  const c = document.querySelector('canvas');
  if (!c) return { no: 'canvas' };
  return { w: c.width, h: c.height, cw: c.clientWidth, ch: c.clientHeight };
});
console.log('gl', glInfo);
console.log('--- logs ---');
for (const l of logs) console.log(l[0], String(l[1]).slice(0, 400));
await page.screenshot({ path: '.tmp-shots/pw-home.png' });
await page.getByRole('button', { name: /Play vs AI/i }).click();
await page.waitForTimeout(7000);
console.log({ canvas2: await page.locator('canvas').count() });
await page.screenshot({ path: '.tmp-shots/pw-game.png' });
console.log('--- more logs ---');
for (const l of logs.slice(-30)) console.log(l[0], String(l[1]).slice(0, 400));
await browser.close();
